export const CHANGE_QUANTITY = 'CHANGE_QUANTITY'
export const ADD_CART = 'ADD_CART'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
export const ADD_WISH_LIST = 'ADD_WISH_LIST'

export const ADD_PREVIEW = 'ADD_PREVIEW'